# Generated by Django 3.2.3 on 2022-08-08 18:43

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('email_address', models.EmailField(max_length=100)),
                ('mobile_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('skills_set', models.TextField(max_length=50, null=True)),
                ('professinal_expeience', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('AP', 'Apply'), ('APL', 'Applied'), ('ACC', 'Accept'), ('RJT', 'Reject')], default='AP', max_length=7)),
                ('document', models.FileField(blank=True, upload_to='documents/')),
            ],
        ),
    ]
