# Generated by Django 3.2.3 on 2022-08-09 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_api', '0002_alter_candidate_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='status',
            field=models.CharField(choices=[('Apply', 'Apply'), ('APPLIED', 'Applied'), ('ACCEPT', 'Accept'), ('REJECT', 'Reject')], default='Apply', max_length=7),
        ),
    ]
