# Generated by Django 3.2.3 on 2022-08-10 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_api', '0004_candidate_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidate',
            old_name='picture',
            new_name='image',
        ),
    ]
